services:
  backup:
    image: localhost/sentinelai_backup:latest
    container_name: sentinelai-backup
    restart: "no"

    environment:
      PGPASSWORD: sentinelai_dev
      POSTGRES_USER: sentinelai
      POSTGRES_DB: sentinelai

    volumes:
      - sentinelai_sentinelai-backups:/backups

    networks:
      - sentinelai

volumes:
  sentinelai_sentinelai-backups:
    external: true
